<div class="container" style="background-image: img/background-login.jpg">


    <div class="col-md-6 col-md-offset-3" style="margin-top: 100px ">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="panel-title" STYLE="text-align: center">
                    <strong>ADMINISTRATOR NOTIFIKASI JADWAL KULIAH</strong>
                    <P>
                        Teknik Informatika Universitas Islam Kuantan Singingi
                    </P>
                </h4>
            </div>
            <div class="panel-body">
                <form action="<?= $this->url->get('session/login') ?>" method="post">
                    <?php $this->flashSession->output() ?>
                    <div class="form-group">
                        <label for="nip_nim">NIDN administrator</label>
                        <input id="nipNim" type="number" class="form-control" name="nip_nim" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-success">Login Administrator</button>
                </form>
            </div>
        </div>

    </div>
</div>


